# Generated by Django 4.2.7 on 2023-11-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
